### ISSUE TITLE
first event no callback

### ISSUE THREAD

**Issue by Chakery** [danielrhodes/Swift-ActionCableClient#23]
after subscribed channel, the first event not callback.

**Comment by danielrhodes** [comment]
Which event are you looking for?

**Comment by danipralea** [comment]
I think the channel doesn't subscribe for some reason, @danielrhodes. If so, I have the same issue many times

**Comment by danielrhodes** [comment]
First of all, did you retain the channel somewhere? I kind of want to change the design of the library somewhat to make this not necessary as I used another realtime library and was unhappy with having a separate channel object.

**Comment by DenHeadless** [comment]
@danielrhodes Actually having a separate Channel object is great. In our app we have Websocket object as a singleton at all times, and create Channel's on demand, whenever user needs them. This flow makes sense also because Starscream library seems to fail to cleanup properly, and crash when we recreate Websocket object =)

**Comment by danipralea** [comment]
I am not, @danielrhodes. I have it like 
```swift

    var webSocketsRoomChannel: Channel {
        let channelIdPayload = ["channel_id" : viewModel.channel?.identifier]
        let channel = SocketRouter.shared.client.create(WebSocketEventsChannel.channel, identifier: channelIdPayload, autoSubscribe: true, bufferActions: true)
        return channel
    }
```

**Comment by Chakery** [comment]
Server-side to send the event changed to asynchronous, it is solved.
